# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/work/verilog/Project/verilog/Vivado/DarkEnHance/DarkEnhance/DarkEnhance.srcs/sources_1/bd/DarkEnhance/ip/DarkEnhance_processing_system7_0_0/DarkEnhance_processing_system7_0_0.xci
# IP: The module: 'DarkEnhance_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/verilog/Project/verilog/Vivado/DarkEnHance/DarkEnhance/DarkEnhance.gen/sources_1/bd/DarkEnhance/ip/DarkEnhance_processing_system7_0_0_1/DarkEnhance_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DarkEnhance_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/work/verilog/Project/verilog/Vivado/DarkEnHance/DarkEnhance/DarkEnhance.srcs/sources_1/bd/DarkEnhance/ip/DarkEnhance_processing_system7_0_0/DarkEnhance_processing_system7_0_0.xci
# IP: The module: 'DarkEnhance_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/verilog/Project/verilog/Vivado/DarkEnHance/DarkEnhance/DarkEnhance.gen/sources_1/bd/DarkEnhance/ip/DarkEnhance_processing_system7_0_0_1/DarkEnhance_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DarkEnhance_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
