# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DarkEnhance/DarkEnhance.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance || ORIG_REF_NAME==DarkEnhance} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_processing_system7_0_0/DarkEnhance_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_processing_system7_0_0 || ORIG_REF_NAME==DarkEnhance_processing_system7_0_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_smartconnect_0_0/DarkEnhance_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_smartconnect_0_0 || ORIG_REF_NAME==DarkEnhance_smartconnect_0_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_rst_ps7_0_50M_0/DarkEnhance_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_rst_ps7_0_50M_0 || ORIG_REF_NAME==DarkEnhance_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_axi_gpio_0_0/DarkEnhance_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_axi_gpio_0_0 || ORIG_REF_NAME==DarkEnhance_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_axi_gpio_1_0/DarkEnhance_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_axi_gpio_1_0 || ORIG_REF_NAME==DarkEnhance_axi_gpio_1_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_blk_mem_gen_0_0/DarkEnhance_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_blk_mem_gen_0_0 || ORIG_REF_NAME==DarkEnhance_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_axi_bram_ctrl_0_0/DarkEnhance_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_axi_bram_ctrl_0_0 || ORIG_REF_NAME==DarkEnhance_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_axi_gpio_1_1/DarkEnhance_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_axi_gpio_1_1 || ORIG_REF_NAME==DarkEnhance_axi_gpio_1_1} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_blk_mem_gen_0_2/DarkEnhance_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_blk_mem_gen_0_2 || ORIG_REF_NAME==DarkEnhance_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_axi_cdma_0_0/DarkEnhance_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_axi_cdma_0_0 || ORIG_REF_NAME==DarkEnhance_axi_cdma_0_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_axi_gpio_1_2/DarkEnhance_axi_gpio_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_axi_gpio_1_2 || ORIG_REF_NAME==DarkEnhance_axi_gpio_1_2} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_DarkEnhance_0_6/DarkEnhance_DarkEnhance_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_DarkEnhance_0_6 || ORIG_REF_NAME==DarkEnhance_DarkEnhance_0_6} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_xlconstant_0_0_1/DarkEnhance_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_xlconstant_0_0 || ORIG_REF_NAME==DarkEnhance_xlconstant_0_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_xlconstant_1_0/DarkEnhance_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_xlconstant_1_0 || ORIG_REF_NAME==DarkEnhance_xlconstant_1_0} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_axi_bram_ctrl_0_2/DarkEnhance_axi_bram_ctrl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_axi_bram_ctrl_0_2 || ORIG_REF_NAME==DarkEnhance_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/DarkEnhance/ip/DarkEnhance_xlconstant_2_1/DarkEnhance_xlconstant_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DarkEnhance_xlconstant_2_1 || ORIG_REF_NAME==DarkEnhance_xlconstant_2_1} -quiet] -quiet

# XDC: e:/work/verilog/Project/verilog/Vivado/DarkEnHance/DarkEnhance/DarkEnhance.gen/sources_1/bd/DarkEnhance/DarkEnhance_ooc.xdc
